FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY app.js /usr/share/nginx/html/app.js
COPY favicon.svg /usr/share/nginx/html/favicon.svg
COPY frontlines_bg1.png /usr/share/nginx/html/frontlines_bg1.png
COPY europe_with_4k_heightmap.glb /usr/share/nginx/html/europe_with_4k_heightmap.glb